name: Build and deploy to S3

on:
  workflow_call:
    inputs:
      bucket:
        required: true
        type: string
      distribution:
        required: true
        type: string
      target:
        required: true
        type: string
      runner:
        description: Runner to run on.
        required: true
        type: string

jobs:
  main:
    runs-on: ${{ inputs.runner }}
    steps:
      - run: sudo apt update && sudo apt install -y curl unzip git
        name: install dependencies

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.6

      - name: Setup NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:${{ inputs.target }}

      - name: Setup AWS CLI
        uses: unfor19/install-aws-cli-action@v1.0.6
        with:
          arch: amd64
          version: 2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: sa-east-1

      - name: Upload to S3
        run: aws s3 sync --delete dist/ 's3://${{ inputs.bucket }}'

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ inputs.distribution }} --paths '/index.html'
